[package]
authors = ["Sean Bowe <ewillbefull@gmail.com>"]
description = "zk-SNARK library"
documentation = "https://github.com/ebfull/bellman"
homepage = "https://github.com/ebfull/bellman"
license = "MIT/Apache-2.0"
name = "bellman"
repository = "https://github.com/ebfull/bellman"
version = "0.0.3"

[dependencies]
rand = "0.3.*"
byteorder = "1.*"
serde = "1.0"
crossbeam = "0.2"
num_cpus = "1.0"

[dev-dependencies]
bincode = "0.8.0"
